aws/porting-assistant-dotnet-client

README.md
Adding section to add thank you section to our README.
=> Update readme to add Thank you section

src/PortingAssistant.Client.Common/Model/ProjectAnalysisResult.cs, src/PortingAssistant.Client.NuGet/PortingAssistantNuGetHandler.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantNugetHandlerTest.cs
*Issue #, if available:*
*Description of changes:*
=> Log the missing package

.github/workflows/build_test.yml, src/PortingAssistant.Client.Analysis/AnalysisHandler.cs, src/PortingAssistant.Client.Analysis/IAnalysisHandler.cs, src/PortingAssistant.Client.Analysis/Utils/ApiCompatiblity.cs, src/PortingAssistant.Client.Analysis/Utils/InvocationExpressionModelToInvocations.cs, src/PortingAssistant.Client.Analysis/Utils/PackageCompatibility.cs, src/PortingAssistant.Client.Client/PortingAssistantClient.cs, src/PortingAssistant.Client.Common/Model/AnalyzerSettings.cs, src/PortingAssistant.Client/PortingAssistantCLI.cs, src/PortingAssistant.Client/Program.cs, tests/PortingAssistant.Client.IntegrationTests/RunWithDotNetFramework.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantAnalysisHandlerTest.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantClientTest.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantResultsToInvocationsWithCompatibilityTest.cs
=> Add targetFramework in AnalyzerSettings(support for dotnet 5)

src/PortingAssistant.Client.Common/Model/PackageVersionPair.cs
=> Fix the duplicated package key issue

src/PortingAssistant.Client.NuGet/PortingAssistantNuGetHandler.cs
=> Add null pointer check to avoid potential dictionary get failure

src/PortingAssistant.Client.Analysis/Utils/ApiCompatiblity.cs, src/PortingAssistant.Client.Analysis/Utils/InvocationExpressionModelToInvocations.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantRecommendationTest.cs
=> Filter only recommendation for current target Framework

version.json
=> Bump version to 1.2.0

src/PortingAssistant.Client.Analysis/AnalysisHandler.cs, src/PortingAssistant.Client.Analysis/PortingAssistant.Client.Analysis.csproj, src/PortingAssistant.Client.Analysis/Utils/InvocationExpressionModelToInvocations.cs, src/PortingAssistant.Client.Analysis/Utils/PackageCompatibility.cs, src/PortingAssistant.Client.Analysis/Utils/ProjectActionsToRecommendedActions.cs, src/PortingAssistant.Client.Common/Model/PortingAction.cs, src/PortingAssistant.Client.Common/Model/RecommendedAction.cs, src/PortingAssistant.Client.Common/Model/SourceFileAnalysisResult.cs, src/PortingAssistant.Client.Common/Model/TextSpan.cs, src/PortingAssistant.Client.Porting/PortingAssistant.Client.Porting.csproj, src/PortingAssistant.Client.Porting/PortingProjectFile/PortingProjectFileHandler.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantClientTest.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantPortingTest.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantResultsToInvocationsWithCompatibilityTest.cs
(1) Use rules engine for porting
(2) Integrate CTA with PortingAssistant
=> CTA integration

src/PortingAssistant.Client.Analysis/PortingAssistant.Client.Analysis.csproj, src/PortingAssistant.Client.Porting/PortingAssistant.Client.Porting.csproj
=> Update CTA version

src/PortingAssistant.Client.Analysis/PortingAssistant.Client.Analysis.csproj, src/PortingAssistant.Client.Porting/PortingAssistant.Client.Porting.csproj
=> Update logging and action names

THIRD-PARTY
Removal of entire license for Project2015To2017 section as discussed during ops meeting 12/21/2020
=> Removal of Project2015To2017

src/PortingAssistant.Client.Analysis/Utils/InvocationExpressionModelToInvocations.cs
=> Add assembly name check to determine source package

src/PortingAssistant.Client.Analysis/PortingAssistant.Client.Analysis.csproj, src/PortingAssistant.Client.Porting/PortingAssistant.Client.Porting.csproj, version.json
Update CTA version to fix bugs
Closes #52 
=> Update CTA version to v1.2.31

src/PortingAssistant.Client.Client/DependencyInjection.cs, src/PortingAssistant.Client.Client/PortingAssistant.Client.Client.csproj, src/PortingAssistant.Client.NuGet/Interfaces/IHttpService.cs, src/PortingAssistant.Client.NuGet/PortingAssistant.Client.NuGet.csproj, src/PortingAssistant.Client.NuGet/Utils/HttpService.cs, src/PortingAssistant.Client/PortingAssistant.Client.CLI.csproj, tests/PortingAssistant.Client.IntegrationTests/PortingAssistant.Client.IntegrationTests.csproj, tests/PortingAssistant.Client.UnitTests/PortingAssistant.Client.UnitTests.csproj
[//]: # 
(1) upgrade dependency package version
(2) add retry logic for http client
[//]: #57 
#57 
=> Upgrade dependency package version and add retry logic for resource download

src/PortingAssistant.Client.Analysis/AnalysisHandler.cs, src/PortingAssistant.Client.Analysis/PortingAssistant.Client.Analysis.csproj, src/PortingAssistant.Client.Client/PortingAssistantClient.cs, src/PortingAssistant.Client.Common/Model/PackageRecommendation.cs, src/PortingAssistant.Client.Porting/IPortingHandler.cs, src/PortingAssistant.Client.Porting/PortingAssistant.Client.Porting.csproj, src/PortingAssistant.Client.Porting/PortingHandler.cs, src/PortingAssistant.Client.Porting/PortingProjectFile/IPortingProjectFileHandler.cs, src/PortingAssistant.Client.Porting/PortingProjectFile/PortingProjectFileHandler.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistant.Client.UnitTests.csproj, tests/PortingAssistant.Client.UnitTests/PortingAssistantPortingTest.cs
=> Add new porting interface with original versions

tests/PortingAssistant.Client.UnitTests/TestXml/ProjectWithPackagesConfig/ProjectWithPackagesConfig.csproj, tests/PortingAssistant.Client.UnitTests/TestXml/SolutionWithProjects/PortingAssistantApiElectron/PortingAssistantApiElectron.csproj, tests/PortingAssistant.Client.UnitTests/TestXml/SolutionWithProjects/PortingAssistantCache/PortingAssistantCache.csproj
Remove references to jquery in test .csproj files
[#64]
=> remove references to jquery in test files

src/PortingAssistant.Client.Analysis/PortingAssistant.Client.Analysis.csproj, src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Porting/PortingAssistant.Client.Porting.csproj, src/PortingAssistant.Client.Porting/packages.lock.json
Add a package lock file to prevent restoring a package with the same name
https://devblogs.microsoft.com/nuget/enable-repeatable-package-restores-using-a-lock-file/
Closes #66 
=> Add package lock file

src/PortingAssistant.Client.Analysis/PortingAssistant.Client.Analysis.csproj, src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Client/PortingAssistantClient.cs, src/PortingAssistant.Client.Common/Model/PortingRequest.cs, src/PortingAssistant.Client.NuGet/Checkers/ExternalCompatibilityChecker.cs, src/PortingAssistant.Client.NuGet/Checkers/PortabilityAnalyzerCompatibilityChecker.cs, src/PortingAssistant.Client.Porting/IPortingHandler.cs, src/PortingAssistant.Client.Porting/PortingAssistant.Client.Porting.csproj, src/PortingAssistant.Client.Porting/PortingHandler.cs, src/PortingAssistant.Client.Porting/PortingProjectFile/IPortingProjectFileHandler.cs, src/PortingAssistant.Client.Porting/PortingProjectFile/PortingProjectFileHandler.cs, src/PortingAssistant.Client.Porting/packages.lock.json, src/PortingAssistant.Client/Program.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistant.Client.UnitTests.csproj, tests/PortingAssistant.Client.UnitTests/PortingAssistantClientTest.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantPortingTest.cs
(1)  Filter 404 Httprequest errors for PortingAssistantClientExpception
(2)  Match projects with corresponding upgraded packages
=> Release 1.4.2 bug fixes

src/PortingAssistant.Client.Client/Model/ProjectApiAnalysisResult.cs
Adding ProjectGuid field to ProjectApiAnalysisResult, to include the same in metrics. Changes for the metrics will be added in the porting-assistant-dotnet-ui repository.
=> Add ProjectGuid to ProjectApiAnalysisResult Model

version.json
=> Bump version 1.5

src/PortingAssistant.Client.Porting/PortingProjectFile/PortingProjectFileHandler.cs
#68 
Filter out failed projects
=> Filter out failed projects when Porting

src/PortingAssistant.Client.Analysis/PortingAssistant.Client.Analysis.csproj, src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Client/PortingAssistant.Client.Client.csproj, src/PortingAssistant.Client.Porting/PortingAssistant.Client.Porting.csproj, src/PortingAssistant.Client.Porting/packages.lock.json, version.json
=> Andrew GitHub fix

src/PortingAssistant.Client.Analysis/PortingAssistant.Client.Analysis.csproj, src/PortingAssistant.Client.Analysis/Utils/ProjectActionsToRecommendedActions.cs, src/PortingAssistant.Client.Common/Model/RecommendedAction.cs, src/PortingAssistant.Client.Porting/PortingAssistant.Client.Porting.csproj, src/PortingAssistant.Client.Porting/packages.lock.json
=> Add textchanges for recommendedActions

src/PortingAssistant.Client.Analysis/AnalysisHandler.cs, src/PortingAssistant.Client.Analysis/PortingAssistant.Client.Analysis.csproj, src/PortingAssistant.Client.Analysis/Utils/InvocationExpressionModelToInvocations.cs, src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Client/PortingAssistant.Client.Client.csproj, src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj, src/PortingAssistant.Client.NuGet/PortingAssistant.Client.NuGet.csproj, src/PortingAssistant.Client.Porting/PortingAssistant.Client.Porting.csproj, src/PortingAssistant.Client.Porting/packages.lock.json, src/PortingAssistant.Client/PortingAssistant.Client.CLI.csproj, tests/PortingAssistant.Client.IntegrationTests/PortingAssistant.Client.IntegrationTests.csproj, tests/PortingAssistant.Client.UnitTests/PortingAssistant.Client.UnitTests.csproj, tests/PortingAssistant.Client.UnitTests/PortingAssistantClientTest.cs
=> Andrew incremental

src/PortingAssistant.Client.Analysis/AnalysisHandler.cs
=> Fix the build failure flag and check IsSyntaxAnalysis flag

src/PortingAssistant.Client.NuGet/Checkers/ExternalCompatibilityChecker.cs
=> Igonre case when check downloaded package name

PortingAssistant.Client.sln, src/PortingAssistant.Client.Telemetry/LogWatcher.cs, src/PortingAssistant.Client.Telemetry/PortingAssistant.Client.Telemetry.csproj, src/PortingAssistant.Client.Telemetry/TelemetryCollector.cs, src/PortingAssistant.Client.Telemetry/TelemetryConfiguration.cs, src/PortingAssistant.Client.Telemetry/packages.lock.json
=> Add telemetry as independent package

src/PortingAssistant.Client.Telemetry/PortingAssistant.Client.Telemetry.csproj, src/PortingAssistant.Client.Telemetry/TelemetryCollector.cs, src/PortingAssistant.Client.Telemetry/packages.lock.json
=> fix the threading issue when write to file

src/PortingAssistant.Client.Analysis/AnalysisHandler.cs
[//]: # Fixes issue #93 by switching building to a single thread
[//]: #93 
=> Switch analysis to a single thread

src/PortingAssistant.Client.Analysis/AnalysisHandler.cs, src/PortingAssistant.Client.Analysis/Utils/ApiCompatiblity.cs, src/PortingAssistant.Client.Analysis/Utils/CodeEntityModelModelToCodeEntities.cs, src/PortingAssistant.Client.Analysis/Utils/CodeEntityModelToCodeEntities.cs, src/PortingAssistant.Client.Analysis/Utils/InvocationExpressionModelToInvocations.cs, src/PortingAssistant.Client.Common/Model/CodeEntityCompatibilityResult.cs, src/PortingAssistant.Client.Common/Model/CodeEntityType.cs, src/PortingAssistant.Client.Common/Model/ProjectAnalysisResult.cs, src/PortingAssistant.Client.Common/Model/ProjectCompatibilityResult.cs, src/PortingAssistant.Client.NuGet/Checkers/ExternalCompatibilityChecker.cs, tests/PortingAssistant.Client.IntegrationTests/RunIncremental.cs, tests/PortingAssistant.Client.IntegrationTests/RunWithDotNetCoreFrameowrk.cs, tests/PortingAssistant.Client.IntegrationTests/RunWithDotNetFramework.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantResultsToInvocationsWithCompatibilityTest.cs
Update PA to include code artifacts that are different from APIs
Closes #101 
=> Add support for counting code entities that are not APIs

src/PortingAssistant.Client.Analysis/AnalysisHandler.cs, src/PortingAssistant.Client.Common/Utils/MemoryUtils.cs, src/PortingAssistant.Client.NuGet/PortingAssistantNuGetHandler.cs, tests/PortingAssistant.Client.IntegrationTests/RunPortingCorrectnessWithDotNetFramework.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantNugetHandlerTest.cs
Added more memory usage logging around main component function calls.
[P49081672](https://sim.amazon.com/issues/P49081672)
=> Add more memory logging around component function calls.

src/PortingAssistant.Client.Porting/PortingProjectFile/PortingProjectFileHandler.cs
=> filter build failed project in successful Porting

src/PortingAssistant.Client.Analysis/Utils/ApiCompatiblity.cs, src/PortingAssistant.Client.Analysis/Utils/CodeEntityModelToCodeEntities.cs
=> Add empty objects for nulls

version.json
=> Set version to '1.8'

src/PortingAssistant.Client.Porting/PortingProjectFile/PortingProjectFileHandler.cs
=> fix: typo in no file access porting result

src/PortingAssistant.Client.Telemetry/TelemetryCollector.cs, src/PortingAssistant.Client/PortingAssistant.Client.CLI.csproj
=> add the version into the solution metrics

src/PortingAssistant.Client.Common/Model/Schema.cs, src/PortingAssistant.Client/PortingAssistant.Client.CLI.csproj, src/PortingAssistant.Client/PortingAssistantCLI.cs, src/PortingAssistant.Client/Program.cs, tests/PortingAssistant.Client.IntegrationTests/RunAnalysisCorrectnessWithDotNetFramework.cs, tests/PortingAssistant.Client.IntegrationTests/RunPortingCorrectnessWithDotNetFramework.cs, tests/PortingAssistant.Client.IntegrationTests/RunSchemaVersionApi.cs
This patch adds an API for user to retrieve the supported schema version. 
Integration tests are added to validate the correctness of the new API.
=> Add schema version API.

src/PortingAssistant.Client/Program.cs
=> Add logs and metrics to the same location with PortingAssistant tool

src/PortingAssistant.Client.Telemetry/Model/SolutionMetrics.cs, src/PortingAssistant.Client.Telemetry/TelemetryCollector.cs
This patch add ApplicationGuid, SolutionGuid and RepositoryUrl to solution metrics.
=> Add Solution Metrics.

src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj, src/PortingAssistant.Client.Porting/packages.lock.json, src/PortingAssistant.Client.Telemetry/packages.lock.json
=> Upgrade cta version.

version.json
=> Set version to '1.10-alpha'

src/PortingAssistant.Client.Analysis/AnalysisHandler.cs, src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj, src/PortingAssistant.Client.Porting/packages.lock.json, src/PortingAssistant.Client.Telemetry/packages.lock.json
=> fix: update CTA version

src/PortingAssistant.Client.NuGet/PortingAssistantNuGetHandler.cs
=> fix: added concurrent dictionary to fix multi threaded write issue

src/PortingAssistant.Client.Client/FileParser/GitConfigFileParser.cs, tests/PortingAssistant.Client.IntegrationTests/TestProjects/NetFrameworkExample-analyze/NetFrameworkExample-package-analysis.json
Check that a remote repo exists before attempting to read it in the git config
Closes #855
=> Check that a remote repo exists before attempting to read it in the git config

.github/workflows/build_test.yml, src/PortingAssistant.Client.Telemetry/Uploader.cs, tests/PortingAssistant.Client.UnitTests/UploaderTest.cs
Unit test for file line map added to track data sent to metrics
=> test: file line map updated on upload

src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj, src/PortingAssistant.Client.Porting/packages.lock.json, src/PortingAssistant.Client.Telemetry/packages.lock.json, tests/PortingAssistant.Client.IntegrationTests/RunIncremental.cs, tests/PortingAssistant.Client.IntegrationTests/TestProjects/NetFrameworkExample-analyze/NetFrameworkExample-api-analysis.json
=> fix: update package reference

src/PortingAssistant.Client.Analysis/AnalysisHandler.cs, src/PortingAssistant.Client.Client/PortingAssistantClient.cs, src/PortingAssistant.Client.Common/Model/ProjectDetails.cs
Add a property in Analysis result for Feature Type
This will be used to enable Feature Type based UI Components
=> feat: add featureType in Analysis Result

version.json
=> Cta pkgversion update

.github/workflows/build_test.yml, src/PortingAssistant.Client.Porting/PortingProjectFile/PortingProjectFileHandler.cs
=> Add hook to detect secrets

src/PortingAssistant.Client.Telemetry/ITelemetryClient.cs, src/PortingAssistant.Client.Telemetry/TelemetryClient.cs, src/PortingAssistant.Client.Telemetry/TelemetryClientConfig.cs, src/PortingAssistant.Client.Telemetry/Uploader.cs, src/PortingAssistant.Client/Program.cs, tests/PortingAssistant.Client.UnitTests/UploaderTest.cs
add ITelemetryClient interface for mocking send, and pass into upload method.
also rename TelemetryConfig to TelemetryClientConfig for clarity
also removed unused parameter in upload method
=> test: file map updated on upload 

.github/workflows/build_test.yml, src/PortingAssistant.Client.Analysis/PortingAssistant.Client.Analysis.csproj, src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Client/PortingAssistant.Client.Client.csproj, src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj, src/PortingAssistant.Client.NuGet/PortingAssistant.Client.NuGet.csproj, src/PortingAssistant.Client.Porting/PortingAssistant.Client.Porting.csproj, src/PortingAssistant.Client.Porting/packages.lock.json, src/PortingAssistant.Client.Telemetry/PortingAssistant.Client.Telemetry.csproj, src/PortingAssistant.Client.Telemetry/packages.lock.json, src/PortingAssistant.Client/PortingAssistant.Client.CLI.csproj, tests/PortingAssistant.Client.IntegrationTests/PortingAssistant.Client.IntegrationTests.csproj, tests/PortingAssistant.Client.UnitTests/PortingAssistant.Client.UnitTests.csproj
* Upgrades the target runtime to .NET 6
* Upgrades minimum set of dependencies to remain compatible with .NET 6
Closes: #1104 
=> upgrade to .NET 6

src/PortingAssistant.Client.Analysis/AnalysisHandler.cs, src/PortingAssistant.Client.Analysis/IAnalysisHandler.cs, src/PortingAssistant.Client.Analysis/Utils/ApiCompatiblity.cs, src/PortingAssistant.Client.Analysis/Utils/CodeEntityModelToCodeEntities.cs, src/PortingAssistant.Client.Analysis/Utils/PackageCompatibility.cs, src/PortingAssistant.Client.Client/PortingAssistantClient.cs, src/PortingAssistant.Client.NuGet/Checkers/InternalPackagesCompatibilityChecker.cs, src/PortingAssistant.Client/PortingAssistantCLI.cs, tests/PortingAssistant.Client.IntegrationTests/RunAnalysisCorrectnessWithDotNetFramework.cs, tests/PortingAssistant.Client.IntegrationTests/RunIncremental.cs, tests/PortingAssistant.Client.IntegrationTests/RunWithDotNetCoreFrameowrk.cs, tests/PortingAssistant.Client.IntegrationTests/RunWithDotNetFramework.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantAnalysisHandlerTest.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantClientTest.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantNugetHandlerTest.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantRecommendationTest.cs, tests/PortingAssistant.Client.UnitTests/PortingAssistantResultsToInvocationsWithCompatibilityTest.cs
=> feat: change default target version from core3.1 to net6.0

src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj, src/PortingAssistant.Client.Porting/packages.lock.json, src/PortingAssistant.Client.Telemetry/packages.lock.json
[//]: # Updated CTA nuget reference to latest alpha
=> Updated CTA reference to latest alpha

src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Porting/packages.lock.json, src/PortingAssistant.Client.Telemetry/packages.lock.json
Updated CTA ref to newest alpha
=> Updated CTA version to newest pre-release

src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj
* Change to csproj updating CTA version included now, was excluded from last commit accidentally
=> Updated csproj for new CTA ref

src/PortingAssistant.Client.Analysis/AnalysisHandler.cs, src/PortingAssistant.Client.Client/PortingAssistantBuilder.cs, src/PortingAssistant.Client.Common/Utils/AnalysisUtils.cs
Export GenerateCompatibilityResults to common.Utils class
Add Encoding.RegisterProvider in ConfigureServices
=> Export incompatibility calculation function

src/PortingAssistant.Client.Telemetry/TelemetryClient.cs, src/PortingAssistant.Client/PortingAssistantCLI.cs, src/PortingAssistant.Client/Program.cs, tests/PortingAssistant.Client.UnitTests/UploaderTest.cs
Add option for Enabled Default Credential
=> Kanikaul sdk

src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj, src/PortingAssistant.Client.Porting/packages.lock.json, src/PortingAssistant.Client.Telemetry/packages.lock.json, tests/PortingAssistant.Client.IntegrationTests/RunAnalysisCorrectnessWithDotNetFramework.cs, tests/PortingAssistant.Client.IntegrationTests/TestProjects/NetFrameworkExample-analyze/NetFrameworkExample-api-analysis.json
update cta version that includes web forms fix
=> chore: update cta version

version.json
merge changes to version back to main after cutting release version
=> chore: update version on main after release

src/PortingAssistant.Client.Analysis/Utils/ApiCompatiblity.cs, src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj, src/PortingAssistant.Client.Porting/packages.lock.json, src/PortingAssistant.Client.Telemetry/packages.lock.json, tests/PortingAssistant.Client.IntegrationTests/RunWithDotNetFramework.cs
update cta package version
also add additional checks for porting verification in integ. tests.
=> chore: update cta

src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj, src/PortingAssistant.Client.Porting/packages.lock.json, src/PortingAssistant.Client.Telemetry/packages.lock.json, tests/PortingAssistant.Client.IntegrationTests/RunIncremental.cs, tests/PortingAssistant.Client.IntegrationTests/TestProjects/NetFrameworkExample-analyze/NetFrameworkExample-api-analysis.json
update CTA package to version 2.4.66
=> chore: update cta package version

version.json
released version 2.3, update main to push 2.4 alpha versions.
=> chore: update version to 2.4 - alpha

src/PortingAssistant.Client/Program.cs
=> feat: add backed error for assessment failure

version.json
=> chore: update version

tests/PortingAssistant.Client.IntegrationTests/RunWithDotNetCoreFrameowrk.cs, version.json
update mainline to track new alpha version
=> chore: update mainline to new alpha version

version.json
=> Set version to '2.8-alpha'

src/PortingAssistant.Client.Client/Reports/ReportExporter.cs, tests/PortingAssistant.Client.UnitTests/ReportExporterTest.cs
- Fix report exporter file path name
- Fix writer by using append instead of write which may delete results of the same run.
=> fix: fix bug in report exporter

version.json
=> Set version to '2.10'

version.json
=> Set version to '2.11'

src/PortingAssistant.Client.Analysis/packages.lock.json, src/PortingAssistant.Client.Client/Reports/ReportExporter.cs, src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj, src/PortingAssistant.Client.Common/Utils/Logging.cs, src/PortingAssistant.Client.Common/Utils/MemoryUtils.cs, src/PortingAssistant.Client.Porting/packages.lock.json, src/PortingAssistant.Client.Telemetry/Model/APIMetrics.cs, src/PortingAssistant.Client.Telemetry/Model/NugetMetrics.cs, src/PortingAssistant.Client.Telemetry/TelemetryCollector.cs, src/PortingAssistant.Client.Telemetry/packages.lock.json, src/PortingAssistant.Client/PortingAssistantCLI.cs, src/PortingAssistant.Client/Program.cs
- Added CLI options that allow customers to toggle the logging level and whether metrics are recorded.
=> Metrics and logging options

version.json
* Update version to 2.15-alpha
=> Update version to 2.15-alpha

tests/PortingAssistant.Client.IntegrationTests/TestProjects/NetFrameworkExample-analyze/NetFrameworkExample-api-analysis.json, tests/PortingAssistant.Client.IntegrationTests/TestProjects/NetFrameworkExample-analyze/NetFrameworkExample-package-analysis.json
=> Update test results to reflect recent fix

src/PortingAssistant.Client.Analysis/AnalysisHandler.cs, src/PortingAssistant.Compatibility.Common/Model/ApiEntity.cs
=> add hashcode and equal for APIEntity class

src/PortingAssistant.Client.Analysis/Utils/CodeEntityModelToCodeEntities.cs, src/PortingAssistant.Client.Common/Model/CodeEntityDetails.cs, tests/PortingAssistant.Client.IntegrationTests/TestProjects/NetFrameworkExample-analyze/NetFrameworkExample-api-analysis.json
add class name in the analysis report
no issue
=> feat: add class name in report

version.json
=> Set version to 3.1-alpha

src/PortingAssistant.Client.Analysis/AnalysisHandler.cs, src/PortingAssistant.Client.Analysis/IAnalysisHandler.cs, src/PortingAssistant.Client.Analysis/Utils/CodeEntityModelToCodeEntities.cs, src/PortingAssistant.Client.Analysis/Utils/CompatibilityCheckerHelper.cs
Add single analysisProject method
=> add new method for analyse project

version.json
Update to next minor alpha version 3.2-alpha
=> Set version to 3.2-alpha

src/PortingAssistant.Compatibility.Common/Utils/RegionalDatastoreService.cs, src/PortingAssistant.Compatibility.Core/CompatibilityCheckerBuilder.cs
Fix the logging issue that RegionalDatastoreService doesn't log into CloudWatch using private logger.
=> fix: logging issue in regional datastore service

src/PortingAssistant.Client.Telemetry/Model/APIMetrics.cs, src/PortingAssistant.Client.Telemetry/Model/NugetMetrics.cs, src/PortingAssistant.Client.Telemetry/PortingAssistant.Client.Telemetry.csproj, src/PortingAssistant.Client.Telemetry/TelemetryCollector.cs
Added optional account id in telemetry metric
=> Added optional account id in telemetry metric
