- src/PortingAssistant.Client.Analysis/AnalysisHandler.cs
- src/PortingAssistant.Client.Analysis/Utils/ApiCompatiblity.cs
- src/PortingAssistant.Client.Analysis/Utils/InvocationExpressionModelToInvocations.cs
- src/PortingAssistant.Client.Analysis/Utils/PackageCompatibility.cs
- src/PortingAssistant.Client.Client/PortingAssistantClient.cs
- src/PortingAssistant.Client.Client/Reports/ReportExporter.cs
- src/PortingAssistant.Client.Common/Model/PackageDetails.cs
- src/PortingAssistant.Client.NuGet/Checkers/ExternalCompatibilityChecker.cs
- src/PortingAssistant.Client.NuGet/Checkers/InternalPackagesCompatibilityChecker.cs
- src/PortingAssistant.Client.NuGet/Checkers/PortabilityAnalyzerCompatibilityChecker.cs
- src/PortingAssistant.Client.NuGet/Interfaces/ICompatibilityChecker.cs
- src/PortingAssistant.Client.NuGet/PortingAssistantNuGetHandler.cs
- src/PortingAssistant.Client.Porting/PortingHandler.cs
- src/PortingAssistant.Client.Porting/PortingProjectFile/PortingProjectFileHandler.cs
- src/PortingAssistant.Client/PortingAssistantCLI.cs
- tests/PortingAssistant.Client.UnitTests/PortingAssistantAnalysisHandlerTest.cs
- tests/PortingAssistant.Client.UnitTests/PortingAssistantClientTest.cs
- tests/PortingAssistant.Client.UnitTests/PortingAssistantInternalNuGetCompatibilityHandlerTest.cs
- tests/PortingAssistant.Client.UnitTests/PortingAssistantNugetHandlerTest.cs
- tests/PortingAssistant.Client.UnitTests/PortingAssistantPortingTest.cs
- tests/PortingAssistant.Client.UnitTests/PortingAssistantRecommendationTest.cs
- tests/PortingAssistant.Client.UnitTests/PortingAssistantResultsToInvocationsWithCompatibilityTest.cs
* Rename methods to follow standards (https://github.com/aws/porting-assistant-dotnet-client/commit/1578991321345afef4bbb7b86bfef4663337fbda, https://github.com/aws/porting-assistant-dotnet-client/commit/4319cebf4ce4da2612ee0386234b402e60f20224).
* Optimize LINQ expressions (178f6e3, c3fb067).
* Remove unused code (147f876, 8219695, f0305b7, 5ce2865).
* Use conditional access and built-in string methods (ff78c96, 9fab849).
* Simplify nested using statements (1513dcc).
Feel free to revert any undesired change/commit.
> Minor style improvements

- src/PortingAssistant.Client/PortingAssistantCLI.cs
Spelling error on the CLI option: output-path
> fix spelling error for CLI option: output-path

- .gitignore
- src/PortingAssistant.Client.Analysis/AnalysisHandler.cs
- src/PortingAssistant.Client.Analysis/Utils/PackageCompatibility.cs
- src/PortingAssistant.Client.Common/Utils/MemoryUtils.cs
- src/PortingAssistant.Client.NuGet/Checkers/ExternalCompatibilityChecker.cs
- tests/PortingAssistant.Client.UnitTests/MemoryUtilsTest.cs
- tests/PortingAssistant.Client.UnitTests/PortingAssistant.Client.UnitTests.csproj
We've seen OutOfMemory exception being thrown few times from PA logs. This patch is to catch the exception and log the memory consumption.
> Hanlde OOM exception and log memory consumptions.

- src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj
- src/PortingAssistant.Client.Common/Utils/FileSystem.cs
- src/PortingAssistant.Client.Common/Utils/FileSystemAccess.cs
- src/PortingAssistant.Client.Porting/PortingProjectFile/PortingProjectFileHandler.cs
Add method to check file write access for directory and its contents, check before porting and only port projects that have permissions to everything within
#88 
> Check file write access before porting projects

- .github/dependabot.yml
- src/PortingAssistant.Client.Analysis/PortingAssistant.Client.Analysis.csproj
- src/PortingAssistant.Client.Analysis/packages.lock.json
- src/PortingAssistant.Client.Client/PortingAssistant.Client.Client.csproj
- src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj
- src/PortingAssistant.Client.NuGet/PortingAssistant.Client.NuGet.csproj
- src/PortingAssistant.Client.Porting/PortingAssistant.Client.Porting.csproj
- src/PortingAssistant.Client.Porting/packages.lock.json
- src/PortingAssistant.Client.Telemetry/PortingAssistant.Client.Telemetry.csproj
- src/PortingAssistant.Client.Telemetry/packages.lock.json
- src/PortingAssistant.Client/PortingAssistant.Client.CLI.csproj
- tests/PortingAssistant.Client.IntegrationTests/PortingAssistant.Client.IntegrationTests.csproj
- tests/PortingAssistant.Client.UnitTests/PortingAssistant.Client.UnitTests.csproj
Closes: #115
* Configures Dependabot to submit a PR to update any Nuget or Porting Assistant dependencies that are not referencing the latest version (1 PR per project dependency)
* This check is performed daily
* **Caveats**
* This yaml file will need to be updated if any new projects are added to the solution or a package from a new nuget feed is referenced
* Dependabot only looks for official releases (pre-releases are not considered)
> Add dependabot

- .github/workflows/build_test.yml
This patch pacakges and publish `PortingAssistant.Client.CLI.exe` to S3 bucket.
We are using `Nerdbank.GitVersioning` for semantic versioning. It
automatically setup the version number for each project and upload them
to our private nuget repo on S3 bucket structured by version. This patch packages
`PortingAssistant.Client.CLI.exe` and upload it to the corresponding
versioned S3 subfolder.
> Package and publish CLI executable to S3 bucket.

- src/PortingAssistant.Client.Client/PortingAssistantClient.cs
ApplyPortingChanges does an aggregation on the RecommendedActions across all projects being ported based on the package ID and generate a dictionary. When more than one project in a solution depend on a same package, the aggregation throws  ThrowAddingDuplicateWithKeyArgumentException due to duplicated key with the same package ID. This patch fix the issue by apply GroupBy before converting to dictionary.
#320 
I've manually tested it againt nopcommerce by porting Nop.Core.csproj and Nop.Services.csproj where both projects depend on Autoflac pacakge. With this change the exception is no longer thrown.
I will add an integration test separately for this error.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Fix ThrowAddingDuplicateWithKeyArgumentException.

- src/PortingAssistant.Client/Program.cs
- tests/PortingAssistant.Client.IntegrationTests/RunPortingCorrectnessWithDotNetFramework.cs
The issue is due to a bug when we are checking for provided projects to port by path but the provided projects are names.
Updated corresponding integration test.
> Portproject skips projects with provided project names.

- src/PortingAssistant.Client.Client/FileParser/GitConfigFileParser.cs
System.NullReferenceException: Object reference not set to an instance of an object.    at PortingAssistant.Client.Client.FileParser.GitConfigFileParser.getGitRepositoryUrl(String gitRepositoryRootPath)    at PortingAssistant.Client.Client.PortingAssistantClient.AnalyzeSolutionAsync(String solutionFilePath, AnalyzerSettings settings)
This is the fix for above exception.
> Fix NullReferenceException.

- src/PortingAssistant.Client/Program.cs
- tests/PortingAssistant.Client.IntegrationTests/RunWithDotNetCoreFrameowrk.cs
- tests/PortingAssistant.Client.IntegrationTests/TestProjects/NetFrameworkExample-analyze/NetFrameworkExample-api-analysis.json
- tests/PortingAssistant.Client.IntegrationTests/TestProjects/NetFrameworkExample-analyze/NetFrameworkExample-package-analysis.json
Add user provided tag to log entry. This helps us to identify the source of assessment/porting errors.
log entry looks like the following with the new change:
```
[2021-11-19 10:57:52 DBG] (Porting Assistant Client CLI) (1.11.15-alpha+86dca5076b) (Drift-1.0.0) PortingAssistant.Client.Analysis.PortingAssistantAnalysisHandler: CallerInfo: PortingAssistantAnalysisHandler.AnalyzeProject
[2021-11-19 10:57:52 DBG] (Porting Assistant Client CLI) (1.11.15-alpha+86dca5076b) (Drift-1.0.0) PortingAssistant.Client.Analysis.PortingAssistantAnalysisHandler: Memory used before collection:       62,316,504
[2021-11-19 10:57:52 DBG] (Porting Assistant Client CLI) (1.11.15-alpha+86dca5076b) (Drift-1.0.0) PortingAssistant.Client.Analysis.PortingAssistantAnalysisHandler: Memory used after full collection: …
```
> Add user provided tag to log entry.

- src/PortingAssistant.Client.Telemetry/Uploader.cs
- src/PortingAssistant.Client/Program.cs
- tests/PortingAssistant.Client.IntegrationTests/RunAnalysisCorrectnessWithDotNetFramework.cs
- tests/PortingAssistant.Client.IntegrationTests/TestProjects/NetFrameworkExample-analyze/NetFrameworkExample-package-analysis.json
- tests/PortingAssistant.Client.IntegrationTests/TestUtils/JsonUtils.cs
Add JSON file to store last line of metrics/logs that were uploaded to telemetry endpoint.
Resolves #857 
Currently this will not introduce any rolling interval to the log/metric files. The upload has the file paths passed directly so more work probably needs to be done to have the files roll each day and ensure we aren't missing and logs from previous days.
> feat: add file line map to track metrics data already sent

- src/PortingAssistant.Client.Analysis/AnalysisHandler.cs
- src/PortingAssistant.Client.Analysis/Utils/PackageCompatibility.cs
- tests/PortingAssistant.Client.IntegrationTests/RunWithDotNetFramework.cs
- tests/PortingAssistant.Client.IntegrationTests/TestProjects/NetFrameworkExample-analyze/NetFrameworkExample-package-analysis.json
- tests/PortingAssistant.Client.UnitTests/PortingAssistantRecommendationTest.cs
* Fix how compatibility is calculated for nuget packages that become incompatible with in a later version (e.g. System.DirectoryServices)
* If a packageId shares a name with an SDK namespace (e.g. System.DirectoryServices), don't analyze it as both a nuget and an SDK. Instead, only analyze it as a nuget.
> Fix compatibility

- src/PortingAssistant.Client.Analysis/AnalysisHandler.cs
- src/PortingAssistant.Client.Analysis/Utils/ApiCompatiblity.cs
- src/PortingAssistant.Client.Analysis/Utils/NugetVersionExtensions.cs
- src/PortingAssistant.Client.Analysis/Utils/NugetVersionHelper.cs
- src/PortingAssistant.Client.Analysis/Utils/PackageCompatibility.cs
- tests/PortingAssistant.Client.UnitTests/NugetVersionExtensionTest.cs
- tests/PortingAssistant.Client.UnitTests/NugetVersionHelperTest.cs
- tests/PortingAssistant.Client.UnitTests/PortingAssistantResultsToInvocationsWithCompatibilityTest.cs
Closes: #1035
* Starting with .NET 5, attributes indicating platform support was made public. This enabled us to properly detect some packages as INCOMPATIBLE once they targeted .NET 5. It also created new compatibility analysis edge cases where packages can be labeled as COMPATIBLE in some versions and labeled as INCOMPATIBLE in later versions.
* Below are the changes in compatibility logic:
* If the current package/api version is greater than any compatible version of that package/api, mark it as COMPATIBLE
* This assumes that once a package became compatible with some version X, it would remain compatible for all versions > X
* It also gave us a best guess for compatibility for the most recent package versions that may not have been analyzed and stored in our datastore yet
* If the …
> Update API and PackageCompatibility logic to support regressions in package compatibility

- src/PortingAssistant.Client.Telemetry/Uploader.cs
- src/PortingAssistant.Client/Program.cs
- tests/PortingAssistant.Client.UnitTests/UploaderTest.cs
Roll telemetry files everyday to prevent the logs/metrics files from becoming too large
Tested locally by running CLI and verifying correct files were being created, then manually adjusted time to next day to verify new files were being created. Verified that unit tests were still passing.
> feat: roll telemetry files daily

- src/PortingAssistant.Client.Analysis/AnalysisHandler.cs
- src/PortingAssistant.Client.Analysis/Utils/CodeEntityModelToCodeEntities.cs
- src/PortingAssistant.Client.Analysis/packages.lock.json
- src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj
- src/PortingAssistant.Client.Porting/packages.lock.json
- src/PortingAssistant.Client.Telemetry/packages.lock.json
when the assembly is mscorlib, we don't have proper rule files for it, so we use the namespace to find potential packages and find the corresponding rule file.
also update cta references for other cta and codelyzer fixes
> fix: parsing packages from mscorlib

- src/PortingAssistant.Client.Telemetry/TelemetryClient.cs
- src/PortingAssistant.Client.Telemetry/TelemetryConfiguration.cs
- src/PortingAssistant.Client.Telemetry/Uploader.cs
- src/PortingAssistant.Client/Program.cs
- tests/PortingAssistant.Client.UnitTests/UploaderTest.cs
Add function to delete old log files while processing metrics.
Refactor the upload logic to be reused within the UI and IDE Extension.
Edit:
Instead of passing a logger into the uploader, instead save error messages in a public property, so the caller can decide what they want to do with error messages. This is mostly just to deduplicate log upload failure errors.
Example of possible usage in the IDE Ext.
> feat: refactor telemetry and clean up old log files

- src/PortingAssistant.Client.Telemetry/TelemetryClient.cs
- tests/PortingAssistant.Client.UnitTests/UploaderTest.cs
- when trying to get telemetry client, add check if profile is blank or null to avoid errors in the credentials chain fetcher.
- add two unit test to verify functionality.
> fix: profile string is null

- src/PortingAssistant.Client/Program.cs
fix trying to upload logs when no profile is provided, this will prevent confusing error to be logged
> fix: log upload message with no profile

- src/PortingAssistant.Client.Analysis/AnalysisHandler.cs
- src/PortingAssistant.Client.Analysis/IAnalysisHandler.cs
- src/PortingAssistant.Client.Analysis/packages.lock.json
- src/PortingAssistant.Client.Client/PortingAssistantClient.cs
- src/PortingAssistant.Client.Common/Model/AnalyzerSettings.cs
- src/PortingAssistant.Client.Common/Model/PortingRequest.cs
- src/PortingAssistant.Client.Common/Model/VisualStudioVersion.cs
- src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj
- src/PortingAssistant.Client.Common/Utils/MemoryUtils.cs
- src/PortingAssistant.Client.NuGet/Checkers/ExternalCompatibilityChecker.cs
- src/PortingAssistant.Client.Porting/IPortingHandler.cs
- src/PortingAssistant.Client.Porting/PortingHandler.cs
- src/PortingAssistant.Client.Porting/PortingProjectFile/IPortingProjectFileHandler.cs
- src/PortingAssistant.Client.Porting/PortingProjectFile/PortingProjectFileHandler.cs
- src/PortingAssistant.Client.Porting/packages.lock.json
- src/PortingAssistant.Client.Telemetry/packages.lock.json
- src/PortingAssistant.Client/Program.cs
- tests/PortingAssistant.Client.UnitTests/MemoryUtilsTest.cs
- tests/PortingAssistant.Client.UnitTests/PortingAssistantClientTest.cs
[//]: # Add visualstudioVersion as a parameter in assessment and porting request
[//]: #  TR IDE 2019 and PA IDE 2019 provides incorrect porting result if client machine have both vs2022 and vs2019 installed.
> fix: add visualstudio version as parameter for assessment and porting

- src/PortingAssistant.Client.Analysis/AnalysisHandler.cs
- src/PortingAssistant.Client.Analysis/IAnalysisHandler.cs
- src/PortingAssistant.Client.Client/PortingAssistantClient.cs
- src/PortingAssistant.Client.Client/Reports/IReportExporter.cs
- src/PortingAssistant.Client.Client/Reports/ReportExporter.cs
Add new interface for Solution Analyze.
> extend-analyzehandler

- src/PortingAssistant.Client.Analysis/packages.lock.json
- src/PortingAssistant.Client.Common/PortingAssistant.Client.Common.csproj
- src/PortingAssistant.Client.Porting/packages.lock.json
- src/PortingAssistant.Client.Telemetry/packages.lock.json
Bump CTA version to 2.12.18-alpha-g36e0ec71a2
> Bump CTA version to 2.12.18-alpha-g36e0ec71a2

- src/PortingAssistant.Client.Analysis/AnalysisHandler.cs
- src/PortingAssistant.Client.Client/PortingAssistantClient.cs
- src/PortingAssistant.Client.Common/Model/ProjectAnalysisResult.cs
- src/PortingAssistant.Client.Common/Model/SolutionAnalysisResult.cs
- src/PortingAssistant.Compatibility.Common/Model/CompatibilityCheckerResponse.cs
Add a HasError property in CompatibilityCheckerResponse class
> add has error property in response

- src/PortingAssistant.Client.Analysis/AnalysisHandler.cs
- src/PortingAssistant.Client.Analysis/CacheService.cs
- src/PortingAssistant.Client.Analysis/ICacheService.cs
- src/PortingAssistant.Client.Analysis/packages.lock.json
- src/PortingAssistant.Compatibility.Common/PortingAssistant.Compatibility.Common.csproj
- src/PortingAssistant.Compatibility.Common/Utils/ApiCompatiblity.cs
- tests/PortingAssistant.Client.IntegrationTests/RunWithDotNetCoreFrameowrk.cs
- tests/PortingAssistant.Compatibility.Core.Tests/UnitTests/ApiCompatibilityTest.cs
> fix-cache-missing

- src/PortingAssistant.Client.Client/DependencyInjection.cs
- src/PortingAssistant.Compatibility.Common/Interface/IRegionalDatastoreService.cs
- src/PortingAssistant.Compatibility.Common/Utils/Constants.cs
- src/PortingAssistant.Compatibility.Common/Utils/RegionalDatastoreService.cs
- src/PortingAssistant.Compatibility.Core/Checkers/ExternalCompatibilityChecker.cs
- src/PortingAssistant.Compatibility.Core/Checkers/NugetCompatibilityChecker.cs
- src/PortingAssistant.Compatibility.Core/Checkers/PortabilityAnalyzerCompatibilityChecker.cs
- src/PortingAssistant.Compatibility.Core/Checkers/SdkCompatibilityChecker.cs
- src/PortingAssistant.Compatibility.Core/CompatibilityCheckerRecommendationActionHandler.cs
- tests/PortingAssistant.Client.UnitTests/PortingAssistantNugetHandlerTest.cs
- tests/PortingAssistant.Compatibility.Core.Tests/UnitTests/NugetHandlerTest.cs
1. Use `IRegionalDatastoreService` as a wrapper of `IHttpService`. The implementation `RegionalDatastoreService` will route service calls to S3 client, and non-service calls to Http service.
2. Route calls to IHttpService if service Lambda environment isn't setup properly, which prevents introducing breaking changes.
> feat: add regional datastore service

- src/PortingAssistant.Client.Telemetry/TelemetryClient.cs
- tests/PortingAssistant.Client.UnitTests/TelemetryClientFactoryTest.cs
- tests/PortingAssistant.Client.UnitTests/TelemetryClientTest.cs
- version.json
[//]: # [(What are you trying to fix? What did you change)](feat: support credentials parameter when generate telemetry client)
> feat: support credentials parameter when generate telemetry client
